MODEL:
  META_ARCHITECTURE: "FsodRCNN"
  PROPOSAL_GENERATOR:
    NAME: "FsodRPN"  
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "FsodRes5ROIHeads"
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    NUM_CLASSES: 1
  BACKBONE:
    FREEZE_AT: 3
DATASETS:
  TRAIN: ("coco_2017_train_nonvoc",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.004
  STEPS: (112000, 120000)
  MAX_ITER: 120000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 30000
  HEAD_LR_FACTOR: 2.0
INPUT:
  FS:
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 10
  MIN_SIZE_TRAIN: (440, 472, 504, 536, 568, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VERSION: 2
